{% render "xpacks/@xpack-dev-tools/xbb-helper/templates/workflows/copyright-liquid.yml" %}

{% if platforms == "all" -%}
{% assign platforms = "linux-x64,linux-arm64,linux-arm,darwin-x64,darwin-arm64,win32-x64" -%}
{% endif -%}
{% assign platforms = platforms | split: "," -%}

name: 'Publish the xPack {{appName}} release'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The semver of the release'
        required: false
        default: 'current'
      helper-git-ref:
        description: 'The helper branch, tag or SHA to checkout'
        required: false
        default: '{{ branch }}'

jobs:
  create-release:
    name: 'Create the pre-release'
    runs-on: ubuntu-22.04

    steps:
      - name: 'Show environment'
        run: |
          uname -a
          lsb_release -sd
          echo "whoami: $(whoami)"
          echo "pwd: $(pwd)"
          ls -lLA
          env | sort | grep -E '^[^ \t]+='

      # https://github.com/actions/checkout
      - name: 'Checkout project'
        uses: actions/checkout@v4
        with:
          fetch-depth: 3

      - name: 'Checkout helper {% raw %}${{ github.event.inputs.helper-git-ref }}{% endraw %}'
        uses: actions/checkout@v4
        with:
          repository: xpack-dev-tools/xbb-helper-xpack
          path: {{ prefix }}/xpacks/@xpack-dev-tools/xbb-helper
          ref: {% raw %}${{ github.event.inputs.helper-git-ref }}{% endraw %}
          fetch-depth: 3

      - name: 'Create body'
        run: |
          ls -lLA
          npm --prefix {{ prefix }} install -dd
          ./{{ prefix }}/node_modules/.bin/liquidjs --context '{ "XBB_RELEASE_VERSION": "{% raw %}${{ github.event.inputs.version }}{% endraw %}" }' --template @{{ prefix }}/templates/body-github-release-liquid.md --output .github/workflows/body-github-release.md
          cat .github/workflows/body-github-release.md

      - name: 'Publish release'
        # https://github.com/ncipollo/release-action
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: false
          bodyFile: '.github/workflows/body-github-release.md'
          commit: '{{ branch }}'
          draft: true
          name: 'xPack {{appName}} v{% raw %}${{ github.event.inputs.version }}{% endraw %}'
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          owner: 'xpack-dev-tools'
          prerelease: true
          replacesArtifacts: false
          repo: '{{appLcName}}-xpack'
          tag: 'v{% raw %}${{ github.event.inputs.version }}{% endraw %}'
          token: {% raw %}${{ secrets.PUBLISH_TOKEN }}{% endraw %}

      - name: 'Gather artifacts'
        run: 'bash {{ prefix }}/xpacks/@xpack-dev-tools/xbb-helper/github-actions/download-all-binaries.sh'

      - name: 'Publish artifacts'
        # https://github.com/ncipollo/release-action
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          artifacts: '~/Downloads/xpack-binaries/{{appLcName}}/*'
          commit: '{{ branch }}'
          draft: true
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          owner: 'xpack-dev-tools'
          prerelease: true
          replacesArtifacts: false
          repo: '{{appLcName}}-xpack'
          tag: 'v{% raw %}${{ github.event.inputs.version }}{% endraw %}'
          token: {% raw %}${{ secrets.PUBLISH_TOKEN }}{% endraw %}
